---
- name: copy master script
  template: src=master.j2 dest=/tmp/master.js

- name: wait for host to become primary
  wait_for: host=0.0.0.0 port=27017 state="started" delay=10
  shell: mongo < /tmp/master.js
