---
- name: check if mongo already installed
  stat: path=/usr/bin/mongo
  register: mongo_bin

- name: MongoDB | Fetch 10Gen signing key
  command: apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv 9DA31620334BD75D9DCB49F368818C72E52529D4
  when: mongo_bin.stat.exists == False

- name: MongoDB | Add 10Gen repository
  shell:
    echo "deb [ arch=amd64 ] https://repo.mongodb.org/apt/ubuntu bionic/mongodb-org/4.0 multiverse" | sudo tee /etc/apt/sources.list.d/mongodb-org-4.0.list
    creates=/etc/apt/sources.list.d/mongodb-org-4.0.list
  when: mongo_bin.stat.exists == False

- name: MongoDB | Copy WIREDTIGER CONF
  template: src=mongod.wiredtiger.j2 dest=/etc/mongod.conf mode=0644

- name: MongoDB | Copy WIREDTIGER Maintenance CONF
  template: src=mongod.conf.maintenance.wiredtiger.j2 dest=/etc/mongod.conf.maintenance mode=0644

- name: install mongodb
  apt: name={{ item }} state=latest update_cache=yes
  with_items:
    - mongodb-org-server
    - mongodb-org-mongos
    - mongodb-org-shell
    - mongodb-org-tools
  when: mongo_bin.stat.exists == False

- name: MongoDB | Create Directory
  file:
    path: "{{ hostvars[inventory_hostname]['db_directory'] }}"
    state: directory
    owner: mongodb
    group: mongodb
    mode: 0755

- name: MongoDB - stop server
  shell: sudo systemctl stop mongod
  when: mongo_bin.stat.exists == False
  ignore_errors: true
